### ISSUE TITLE
Week 2 - Team Review Ticket

### ISSUE THREAD

**Issue by allisonthuang** [christinlee367/womenInSTEMandDavid#15]
[Static site link](https://christinlee367.github.io/womenInSTEMandDavid/)

- [ ] Project Owner / Sponsor presentation, results of review, PII concerns, hosting plan, and [software license](https://christinlee367.github.io/womenInSTEMandDavid/visual)
- [ ] [1st Code in GitHub with software license per 5.5](https://github.com/christinlee367/womenInSTEMandDavid)

**Comment by jm1021** [comment]
Del Norte sport and lacrosse team.   Everything you need to know about lacrosse.  Sponsor is Ms Sullivan.

Starting Wires. 

Having a place for Parent sign up, sponsors sign up, upload photos.

Football site and Volleyball are working examples.  

Creative Commons license.   PII concerns, security phrase on login.   PUSD AWS for deployment.

Question about MaxPreps.   But this was more for community.

Can parents upload?   Privacy policy.

Suggestion about college recruiting angle in the features.

Question about access control.   Upload photo requires login, but not viewing.
