### ISSUE TITLE
Week 9: Bria Review Ticket

### ISSUE THREAD

**Issue by B-G101** [christinlee367/womenInSTEMandDavid#43]
Individual: 1.5/1.8

Individual Expectation - Weekly (Wednesday at BOD, 8:00am)

- In ticket, review comments with Scrum Team crossover and Scrum Master
     - Score of 2 points, 1.8 maximum
          - Meeting 5 hours with commit evidence is minimum for .9
          - Justification: Though I had commits this week and was making progress on the website however I don't think I've contributed as much as I could have.
          - Justification: [Link to Commits from the Week](https://github.com/christinlee367/womenInSTEMandDavid/commits?author=B-G101)
          - Meeting team and sponsor objectives
          - Justification: I worked on the team roster page and the coaches' bio page which were both requested by our sponsor Ms. Sullivan.

**Comment by paigemccartin** [comment]
Score: 1.5/1.8 By Paige McCartin
- Comits are visible and valid
- pages were requested by sponser
- website is neat and organized
- created roster
- did CRUD log in page

**Comment by allisonthuang** [comment]
# Scrum Master Review
- 1.8/1.8
- Great work on CRUD. Thank you for really pulling through here with our navbar and all that stuff
- Solid work on roster. Helping other group members make progress and that page more relevant
